apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8-deployment
  namespace: kubernetes-cluster-{{USERNAME}}
  labels:
    app: app-{{USERNAME}}
spec:
  selector:
    matchLabels:
      app: app-{{USERNAME}}
  replicas: 4
  template:
    metadata:
      labels:
        app: app-{{USERNAME}}
    spec:
      containers:
      - name: app-{{USERNAME}}
        image: {{USERNAME}}/i-{{USERNAME}}-{{BRANCH_NAME}}:latest
        env:
          - name: deployment.branch
            value: {{BRANCH_NAME}} 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: kubernetes-cluster-{{USERNAME}}
  name: app-{{USERNAME}}
spec:
  type: LoadBalancer
  selector:
    app: app-{{USERNAME}}
  ports:
  - port: {{PORT}}
    targetPort: 8080
    protocol: TCP

