apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8-deployment-{{BRANCH_NAME}}
  namespace: kubernetes-cluster-{{USERNAME}}
  labels:
    app: app-{{USERNAME}}-{{BRANCH_NAME}}
spec:
  selector:
    matchLabels:
      app: app-{{USERNAME}}-{{BRANCH_NAME}}
  replicas: 4
  template:
    metadata:
      labels:
        app: app-{{USERNAME}}-{{BRANCH_NAME}}
    spec:
      containers:
      - name: app-{{USERNAME}}-{{BRANCH_NAME}}
        image: {{DOCKERHUBUSERNAME}}/i-{{USERNAME}}-{{BRANCH_NAME}}:{{BUILD_NUMBER}}
        env:
          - name: deployment.branch
            value: {{BRANCH_NAME}} 
        ports:
        - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata: 
    namespace: kubernetes-cluster-{{USERNAME}}
    name: app-{{USERNAME}}-{{BRANCH_NAME}}
spec: 
   type: NodePort
   selector:
       app: app-{{USERNAME}}-{{BRANCH_NAME}}
   ports:
      - protocol: TCP
        nodePort: {{PORT}}
        port: 8100
        targetPort: 8100              

